vim.wo.number = true -- make line nubmers default
vim.o.relativenumber = true -- relative line numbers
vim.o.clipboard = 'unnamedplus' --Sync clipboard between OS and nvim. 
vim.o.linebreak = true --Companion to wrap, don't split words
vim.o.mouse = 'a' --enables mouse mode
vim.o.autoindent = true 
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.shiftwidth = 4
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.expandtab = true
vim.o.scrolloff = 4
vim.o.cursorline = false
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.backup = false -- Creates a backup file (default: false)i
vim.opt.cursorline = true
vim.opt.guicursor = 'n-v-c-i:block'
